apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: todoozle
  annotations:
    kubernetes.io/ingress.class: nginx
  name: todoozle
spec:
  rules:
  - host: {{ .Values.todoozle.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.todoozle.service.name }}
          servicePort: {{ .Values.todoozle.service.port }}
        path: /