apiVersion: v1
kind: Secret
metadata:
  name: todoozle-secret-key
  labels:
    app: todoozle
    env: {{ .Values.env }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  secret-key: {{ .Values.todoozle.secret_key | b64enc | quote }}