{{- if eq .Values.env "dev" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: todoozle
  annotations:
    kubernetes.io/ingress.class: nginx
  name: todoozle
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.todoozle.service.name }}
          servicePort: {{ .Values.todoozle.service.port }}
        path: /
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: todoozle
  name: {{ .Values.todoozle.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.todoozle.service.port }}
    protocol: TCP
    targetPort: {{ .Values.todoozle.service.targetPort }}
  selector:
    app: todoozle
  {{- if eq .Values.env "dev" }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  loadBalancerSourceRanges:
  {{- range .Values.todoozle.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end }}