todoozle:
    secret_key: ENC[AES256_GCM,data:yAuZ0PSDdRnTWHsOm6Z34GKklbkeIMHp,iv:Q5vIHngvKf//qkt81KfHaWkKuV3bIHEe2s/lWaYfcqM=,tag:XZs6zs1s69xECT3nHRKASg==,type:str]
    service:
        loadBalancerSourceRanges:
        - ENC[AES256_GCM,data:yw42D7odmYbVdTrnHJmRdnIU,iv:iWR/g4g/eVhTjOaHw5g/XsPpr5XtOlia5qolev4ORus=,tag:I6ts0956c5mTs1efE6Svvg==,type:str]
postgres_common:
    pass: ENC[AES256_GCM,data:DAHpnyEecqDS9ZSQpiytJDGj5Kop8VYV,iv:gKEubaNz3MXpagxV0qpZPN+VZUK6j1NBjB1jeP5xqTQ=,tag:Umt61XkVzoFrOQMcbC0w1w==,type:str]
postgres_replica:
    reppass: ENC[AES256_GCM,data:RpDh2XUVnsk29z+g5uUsfUDH9vT5CNzK,iv:TQ7QrB3sqzRPT3q5ajizjGwJwoKVOHz4Pkxu1DC3C4A=,tag:Zp3dNnGtIuiRNJkNKh1YLQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/k8s-flask-postgres-app/locations/global/keyRings/sops/cryptoKeys/todoozle-staging-sops-key
        created_at: '2020-09-28T01:39:00Z'
        enc: CiQA9JIZH+dI2/qiBFO/eITZg7iR32aopZxu0gV9rcDX8a2KUr8SSQAYC6F8bPmU/UQS3BQdeniO8qd0MIKBAhT+WutUWEEkdhV27vIhnwLgY1EueDg37JJQ1arvmJQwgtiaunzuh5uhOg7JC3uUI0c=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-28T05:40:42Z'
    mac: ENC[AES256_GCM,data:5sGbs/UM9V29AU30g2KNbSzLiebVZ+XCTkdjf7SBUY7YjzQkbhpNVpXQcRcUnV+FezUEd1Aolo4iIyT0X23T2978uteF2NiwehBMWbB/4fpsDZzcMvOlinhT2KqwdDmlhDE3gDxwMRAs/0bG3/SriiHcLT4yQBXkEySVihVH5DA=,iv:V7Cm6SiKRpEtreReSADK/8bUcjaiAr6GtRiPVNAqLvc=,tag:aEgWsd8YmAh3Arw9Hg+39g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
