"""empty message

Revision ID: e054dae5e22b
Revises: 
Create Date: 2020-09-23 02:44:19.111596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e054dae5e22b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoitem')
    # ### end Alembic commands ###
