# This secret is somewhat unecessary as SECRET_KEY won't be used for the DB migrate 
# but in the interest of not having it set to a default we will keep this for now
apiVersion: v1
kind: Secret
metadata:
  name: todoozle-migrate-secret-key
  labels:
    app: todoozle-migrate
    env: {{ .Values.env }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  secret-key: {{ .Values.todoozle.secret_key | b64enc | quote }}