apiVersion: v1
kind: Secret
metadata:
  name: postgres-main-db-pass
  labels:
    app: postgres-main
    env: {{ .Values.env }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  pass: {{ .Values.postgres_common.pass | b64enc | quote }}