#!/bin/bash 

##
# scripts/deploy_all
# This script is meant to be run against a fresh Kubernetes cluster
# Please only run this to seed the environment, all other deploy actions
# should make use of the scripts/deploy script

usage() {
  echo "Usage: $0 -e [dev|staging] " 1>&2 
}

[[ -z "$TD_PROJECT_ROOT" ]] && echo "TD_PROJECT_ROOT not set, exiting.." && exit 1

CHARTS_DIR="${TD_PROJECT_ROOT}/helm_charts"
CONFIG_DIR="${TD_PROJECT_ROOT}/config"

while getopts "c:e:" opts; do
  case "${opts}" in
    e)
      DEPLOY_ENV=${OPTARG}
      ;;
    *)
      usage && exit 1
      ;;
  esac
done

# Create the ingress-nginx namespace
kubectl create namespace ingress-nginx || exit 1

# Install the ingress controller
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx || exit 1
helm install --namespace ingress-nginx ingress-nginx ingress-nginx/ingress-nginx || exit 1