#!/bin/bash

###
# scripts/release
# The release script pushes the current version and last built Docker image
# to Docker Hub

[[ -z "$TD_PROJECT_ROOT" ]] && echo "TD_PROJECT_ROOT not set, exiting.." && exit 1

APP_SOURCE_DIR="${TD_PROJECT_ROOT}/src"
VERSION=$(cat "${APP_SOURCE_DIR}/version")

IMAGE=cstubbs/todoozle

sudo docker push "${IMAGE}:${VERSION}"
sudo docker push "${IMAGE}:latest"