apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replica-config
  labels:
    app: postgres-replica
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  POSTGRES_DB: {{ .Values.postgres_common.db }}
  POSTGRES_USER: {{ .Values.postgres_common.user }}