apiVersion: v1
kind: Secret
metadata:
  name: postgres-replica-db-credentials
  labels:
    app: postgres-replica
    env: {{ .Values.env }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  pass: {{ .Values.postgres_common.pass | b64enc | quote }}
  reppass: {{ .Values.postgres_replica.reppass | b64enc | quote }}
