apiVersion: v1
kind: Service
metadata:
  labels:
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: postgres-replica
  name: postgres-replica
spec:
  ports:
  - name: postgres-repl
    port: {{ .Values.postgres_replica.service.port }}
    protocol: TCP
    targetPort: {{ .Values.postgres_replica.ss.containerPort }}
  selector:
    app: postgres-replica
  type: ClusterIP
