env: dev

todoozle:
  service:
    servicePort: 80
    targetPort: 5000
  deployment:
    replicas: 1
    containerPort: 5000
    resources:
      requests:
        cpu: 100m
        memory: 75Mi
      limits:
        cpu: 150m
        memory: 150Mi

postgres:
  main:
