env: dev

todoozle:
  image_tag: 0.2.0
  secret_key: super-s3cure-dev-s3cret
  ingress:
    host: localhost
  service:
    name: todoozle
    port: 5000
    targetPort: 5000
  deployment:
    replicas: 1
    containerPort: 5000
    resources:
      requests:
        cpu: 100m
        memory: 75Mi
      limits:
        cpu: 150m
        memory: 150Mi

postgres_common:
  user: todoozle
  db: todoozle
  pass: supers3cret

postgres_main:
  service:
    name: postgres-main
    port: 15432
  # StatefulSet config
  ss:
    containerPort: 5432
    dataVolumeMountPath: /var/lib/postgresql/data
    # This is the default for Docker Desktop Kubernetes cluster
    storageClass: hostpath
    resources:
      req:
        storage: 256Mi